### ISSUE TITLE
Scan return wrong NULL value.

### ISSUE THREAD

**Issue by RonyK** [RonyK/SuaDB#12]
When request value on coordinate which has NULL value, ArrayFile return wrong value.

For example :

> [[[(0,100,1),(1,99,),(2,,3),(,97,4)],[(4,,),(,95,),(9,,),(,,)],[(9,92,),(9,91,),(,,11),(11,89,)],[(12,88,13),(,13,14),(14,86,15),(15,85,16)]]]
> new transaction: 4
> Assert (0, 0, 0) a : 0, b : 100, c : 1
> True
> Assert (0, 0, 1) a : 1, b : 99, **c : 3**
> False

At second assertion, attribute 'c' has null value but, arrayFile gives wrong value '3'.
I guess it return the value of the next() coordinate.

Reference SuaDB_3D_ABC > test_30_scan_array()

**Comment by DalsuChoi** [comment]
This is not a bug

**Comment by RonyK** [comment]
@choids Please make function in ArrayFile class for checking whether current value is null or not.

**Comment by RonyK** [comment]
I will add isNull() function in all scan class.

**Comment by RonyK** [comment]
Now we fixed.
