### ISSUE TITLE
Multiple array create bug

### ISSUE THREAD

**Issue by RonyK** [RonyK/SuaDB#13]
I can't make multiple arrays.
When I try to make these arrays, SuaDB wait for a while and fail the create query for these arrays.

Below is error message and StackTrace message

> java.lang.IllegalArgumentException: Negative position
> 
> 	at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:755)
> 	at suadb.file.FileMgr.write(FileMgr.java:84)
> 	at suadb.file.FileMgr.append(FileMgr.java:101)
> 	at suadb.file.Page.append(Page.java:114)
> 	at suadb.buffer.Buffer.assignToNew(Buffer.java:80)
> 	at suadb.buffer.ChunkBuffer.assignToNew(ChunkBuffer.java:249)
> 	at suadb.buffer.ChunkBufferMgr.pinNew(ChunkBufferMgr.java:90)
> 	at suadb.buffer.BufferMgr.pinNew(BufferMgr.java:82)
> 	at suadb.tx.ChunkList.pinNew(ChunkList.java:48)
> 	at suadb.tx.Transaction.append(Transaction.java:238)
> 	at suadb.record.RecordFile.appendBlock(RecordFile.java:163)
> 	at suadb.record.RecordFile.insert(RecordFile.java:124)
> 	at suadb.metadata.ArrayMgr.createArray(ArrayMgr.java:92)
> 	at suadb.metadata.MetadataMgr.createArray(MetadataMgr.java:31)
> 	at suadb.planner.BasicUpdatePlanner.executeCreateArray(BasicUpdatePlanner.java:86)
> 	at suadb.planner.Planner.executeUpdate(Planner.java:56)
> 	at suadb.server.SuaDBTest.test_10_create_1D_array_with_underbar(SuaDBTest.java:96)

**Comment by dilve** [comment]
I will look into his issue

**Comment by dilve** [comment]
Fixed
The bug was occurred because block had no information about the chunk number that it corresponds to.
The chunk number is essential for metadata related tables since the block number is managed by chunk number.

**Comment by RonyK** [comment]
Oh, really good job 👍
