### ISSUE TITLE
Input insert data at wrong coordinate.

### ISSUE THREAD

**Issue by RonyK** [RonyK/SuaDB#15]
I create array below,
> Execute Update Query : CREATE ARRAY TARRAY3DABC<   a : int,   b : int,   c : int>[x = 0:1,2, y = 0:3,4, z = 0:1,2]

and insert DummyData 'ArrayDummy_3A_3D' in test/suadb/test/DummyData class.
> [[[(0,100,1),(1,99,),(2,,3),(,97,4)],[(4,,),(,95,),(9,,),(,,)],[(9,92,),(9,91,),(,,11),(11,89,)],[(12,88,13),(,13,14),(14,86,15),(15,85,16)]]]

But it is inserted at wrong coordinate.
(0, 0, 0) a : 0,	b : 100,	c : 1	Expect (0,100,1)	True
(0, 0, 1) a : 1,	b : 99,	c : 3	Expect (1,99,)	True
(0, 1, 0) a : 2,	b : 97,	c : 3	Expect (4,,)

I guess it's because of chunk size.
Below are result of test
> (0, 0, 0) a : 0,	b : 100,	c : 1	Expect (0,100,1)
> (0, 0, 1) a : 1,	b : 99,	c : 3	Expect (1,99,)
> (0, 1, 0) a : 2,	b : 97,	c : 3	Expect (4,,)
> (0, 1, 1) a : 4,	b : 97,	c : 4	Expect (,95,)
> (0, 2, 0) a : 4,	b : 95,	c : 11	Expect (9,92,)
> (0, 2, 1) a : 9,	b : 95,	c : 11	Expect (9,91,)
> (0, 3, 0) a : 9,	b : 92,	c : 11	Expect (12,88,13)
> ...

Reference SiaDB_3D_ABC>test_30_scan_array() test

**Comment by RonyK** [comment]
In case of [x = 0:10,2, y = 0:20,2, z = 0:30,2]

Execute Query : SCAN(TARRAY3DABC)
(0, 0, 0) a : 0,	b : 100,	c : 1	Expect (0,100,1)	True
(0, 0, 1) a : 1,	b : 99,	c : 3	Expect (1,99,)	True
(0, 0, 2) a : 2,	b : 97,	c : 3	Expect (2,,3)	True
(0, 0, 3) a : 4,	b : 97,	c : 4	Expect (,97,4)	True
(0, 0, 4) a : 4,	b : 95,	c : 11	False
(0, 0, 5) a : 9,	b : 95,	c : 11	False
(0, 0, 6) a : 9,	b : 92,	c : 11	False
(0, 0, 8) a : 9,	b : 92,	c : 11	False
(0, 0, 9) a : 9,	b : 91,	c : 11	False
(0, 0, 10) a : 11,	b : 89,	c : 11	False
(0, 0, 11) a : 11,	b : 89,	c : 13	False
(0, 0, 12) a : 12,	b : 88,	c : 13	False
(0, 0, 13) a : 14,	b : 13,	c : 14	False
(0, 0, 14) a : 14,	b : 86,	c : 15	False
(0, 0, 15) a : 15,	b : 85,	c : 16	False

**Comment by DalsuChoi** [comment]
Maybe fixed.

Add exception handling in input().
