### ISSUE TITLE
Bug in parser input()

### ISSUE THREAD

**Issue by RonyK** [RonyK/SuaDB#9]
Lexar splits inputfile path used in input operator; 'INPUT([ARRAY], [INPUT_FILE_PATH]);' because [INPUT_FILE_PATH] has several delimiters like colon(:), backslash(\), slash(/) and period(.).

Expect format of input operator AFL is

> INPUT(ArrayName, 'FILE_PATH')

and string of file path is surrounded by apostrophe.

We have to fix input() function in Parser class
```
	// Methods for parsing input commands
	public InputArrayData input() {
		lex.eatKeyword("input");
		lex.eatDelim('(');
		String arrayname = lex.eatId();
		lex.eatDelim(',');
		String inputfile = lex.eatId();  // Error in here
		lex.eatDelim(')');
		
		return new InputArrayData(arrayname, inputfile);
	}
```

**Comment by Aram-Kim** [comment]
I will fix it

**Comment by RonyK** [comment]
@Aram-Kim  Good!

**Comment by RonyK** [comment]
Lexar eat back slash delimiter.
Reopen issue.

**Comment by RonyK** [comment]
Fixed
